"""Task 6 — Legacy `--skill` value error path.

After the 0.10.0 rename, `--skill memory` / `--skill ontology` /
`--skill self-learning` are rejected with a migration hint pointing
at the new prefixed names. The hint is generated by inspecting
argparse's "invalid choice" message in the existing ArgumentError
catch (cli_install_skills.run_install_skills).
"""

from __future__ import annotations

import pytest

from sage_memory.cli_install_skills import run_install_skills


@pytest.mark.parametrize("legacy_name,new_name", [
    ("memory", "sage-memory"),
    ("ontology", "sage-ontology"),
    ("self-learning", "sage-self-learning"),
])
def test_legacy_skill_name_rejected_with_migration_hint(
    legacy_name, new_name, capsys,
):
    code = run_install_skills([
        "claude-code", "--project", "--skill", legacy_name,
    ])
    assert code == 1
    err = capsys.readouterr().err
    # argparse's "invalid choice" path
    assert "invalid choice" in err
    assert f"'{legacy_name}'" in err
    # Migration hint with version + the new name
    assert "0.10.0" in err
    assert new_name in err
    assert "CHANGELOG" in err


def test_new_skill_name_accepted(capsys):
    """Sanity: passing the new prefixed name doesn't trigger the
    migration error path."""
    code = run_install_skills([
        "claude-code", "--project", "--skill", "sage-memory",
        "--dry-run",
    ])
    # Returns 0 on dry-run success
    assert code == 0
    err = capsys.readouterr().err
    assert "invalid choice" not in err
    assert "CHANGELOG" not in err
